const { StyleSheet } = require('react-native')

const Zero = 0
const One = 5
const Two = 10
const Three = 12
const Four = 15
const Five = 18

const spacing = StyleSheet.create({
    pZero: { padding: Zero },
    ptZero: { paddingTop: Zero },
    pbZero: { paddingBottom: Zero },
    plZero: { paddingLeft: Zero },
    prZero: { paddingRight: Zero },
    pxZero: { paddingHorizontal: Zero },
    pyZero: { paddingVertical: Zero },
    mZero: { margin: Zero },
    mtZero: { marginTop: Zero },
    mbZero: { marginBottom: Zero },
    mlZero: { marginLeft: Zero },
    mrZero: { marginRight: Zero },
    mxZero: { marginHorizontal: Zero },
    myZero: { marginVertical: Zero },

    pOne: { padding: One },
    ptOne: { paddingTop: One },
    pbOne: { paddingBottom: One },
    plOne: { paddingLeft: One },
    prOne: { paddingRight: One },
    pxOne: { paddingHorizontal: One },
    pyOne: { paddingVertical: One },
    mOne: { margin: One },
    mtOne: { marginTop: One },
    mbOne: { marginBottom: One },
    mlOne: { marginLeft: One },
    mrOne: { marginRight: One },
    mxOne: { marginHorizontal: One },
    myOne: { marginVertical: One },

    pTwo: { padding: Two },
    ptTwo: { paddingTop: Two },
    pbTwo: { paddingBottom: Two },
    plTwo: { paddingLeft: Two },
    prTwo: { paddingRight: Two },
    pxTwo: { paddingHorizontal: Two },
    pyTwo: { paddingVertical: Two },
    mTwo: { margin: Two },
    mtTwo: { marginTop: Two },
    mbTwo: { marginBottom: Two },
    mlTwo: { marginLeft: Two },
    mrTwo: { marginRight: Two },
    mxTwo: { marginHorizontal: Two },
    myTwo: { marginVertical: Two },

    pThree: { padding: Three },
    ptThree: { paddingTop: Three },
    pbThree: { paddingBottom: Three },
    plThree: { paddingLeft: Three },
    prThree: { paddingRight: Three },
    pxThree: { paddingHorizontal: Three },
    pyThree: { paddingVertical: Three },
    mThree: { margin: Three },
    mtThree: { marginTop: Three },
    mbThree: { marginBottom: Three },
    mlThree: { marginLeft: Three },
    mrThree: { marginRight: Three },
    mxThree: { marginHorizontal: Three },
    myThree: { marginVertical: Three },

    pFour: { padding: Four },
    ptFour: { paddingTop: Four },
    pbFour: { paddingBottom: Four },
    plFour: { paddingLeft: Four },
    prFour: { paddingRight: Four },
    pxFour: { paddingHorizontal: Four },
    pyFour: { paddingVertical: Four },
    mFour: { margin: Four },
    mtFour: { marginTop: Four },
    mbFour: { marginBottom: Four },
    mlFour: { marginLeft: Four },
    mrFour: { marginRight: Four },
    mxFour: { marginHorizontal: Four },
    myFour: { marginVertical: Four },

    pFive: { padding: Five },
    ptFive: { paddingTop: Five },
    pbFive: { paddingBottom: Five },
    plFive: { paddingLeft: Five },
    prFive: { paddingRight: Five },
    pxFive: { paddingHorizontal: Five },
    pyFive: { paddingVertical: Five },
    mFive: { margin: Five },
    mtFive: { marginTop: Five },
    mbFive: { marginBottom: Five },
    mlFive: { marginLeft: Five },
    mrFive: { marginRight: Five },
    mxFive: { marginHorizontal: Five },
    myFive: { marginVertical: Five }
})

export default spacing